### ISSUE TITLE
worlds don't load with the newest update, no crash log...

### ISSUE THREAD

**Issue by Worgrick** [shedaniel/gravel-ores#1]
thanks

**Comment by shedaniel** [comment]
Please fill up your issue with the latest.log, `thanks` is not descriptive at all, thanks.

**Comment by Worgrick** [comment]
It does not give a log

**Comment by Worgrick** [comment]
How?

**Comment by shedaniel** [comment]
Send the `latest.log` from the `logs` folder.

Please use a paste site, instead of dumping it in chat. 

Here's a list of some paste sites and their size limits:
    https://gist.github.com/: 100MB Requires member (Free)
    https://pastebin.com/: 512KB as guest, 10MB as Pro ($$$) 
    https://hastebin.com/ 400KB as guest
    https://paste.ee/: 1MB as guest, 6MB as member (Free)
    https://paste.gg/: 15MB as guest
